In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

In [3]:
df=pd.read_csv('tiitanic.csv',usecols=['Age','Fare','Survived'])

In [4]:
df.dropna(inplace=True)

In [5]:
df

     Survived   Age     Fare
0           0  22.0   7.2500
1           1  38.0  71.2833
2           1  26.0   7.9250
3           1  35.0  53.1000
4           0  35.0   8.0500
..        ...   ...      ...
885         0  39.0  29.1250
886         0  27.0  13.0000
887         1  19.0  30.0000
889         1  26.0  30.0000
890         0  32.0   7.7500

[714 rows x 3 columns]

In [6]:
X=df.iloc[:,1:3]
Y=df.iloc[:,0]

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [8]:
clf=DecisionTreeClassifier()
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [9]:
y_pred=clf.predict(X_test)

In [10]:
accuracy_score(y_test,y_pred)

0.6223776223776224

In [11]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,Y,cv=10,scoring='accuracy'))

np.float64(0.6247456964006259)

In [12]:
kbin_age=KBinsDiscretizer(n_bins=15,encode='ordinal',strategy='quantile')
kbin_fare=KBinsDiscretizer(n_bins=15,encode='ordinal',strategy='quantile')

In [13]:
trf=ColumnTransformer([
    ('first',kbin_age,[0]),
    ('second',kbin_fare,[1])
])

In [14]:
X_train_transformed=trf.fit_transform(X_train)
X_test_transformed=trf.transform(X_test)

C:\Users\mazda computer\anaconda3\Lib\site-packages\sklearn\preprocessing\_discretization.py:296: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(
C:\Users\mazda computer\anaconda3\Lib\site-packages\sklearn\preprocessing\_discretization.py:296: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

In [15]:
clf=DecisionTreeClassifier()
clf.fit(X_train_transformed,y_train)
y_pred=clf.predict(X_test_transformed)
accuracy_score(y_test,y_pred)

0.6363636363636364

In [16]:
df=pd.read_csv('tiitanic.csv',usecols=['Survived','Parch','SibSp','Fare','Age'])

In [17]:
df

     Survived   Age  SibSp  Parch     Fare
0           0  22.0      1      0   7.2500
1           1  38.0      1      0  71.2833
2           1  26.0      0      0   7.9250
3           1  35.0      1      0  53.1000
4           0  35.0      0      0   8.0500
..        ...   ...    ...    ...      ...
886         0  27.0      0      0  13.0000
887         1  19.0      0      0  30.0000
888         0   NaN      1      2  23.4500
889         1  26.0      0      0  30.0000
890         0  32.0      0      0   7.7500

[891 rows x 5 columns]

In [18]:
df['Family']=df['SibSp']+df['Parch']

In [19]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [23]:
df.dropna(inplace=True)

In [25]:
X=df.drop(columns=['Survived'])
Y=df['Survived']

In [39]:
X.shape

(714, 3)

In [65]:
X

      Age     Fare  Family
0    22.0   7.2500       1
1    38.0  71.2833       1
2    26.0   7.9250       0
3    35.0  53.1000       1
4    35.0   8.0500       0
..    ...      ...     ...
885  39.0  29.1250       5
886  27.0  13.0000       0
887  19.0  30.0000       0
889  26.0  30.0000       0
890  32.0   7.7500       0

[714 rows x 3 columns]

In [47]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [48]:
clf=DecisionTreeClassifier()
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
accuracy_score(y_test,y_pred)

0.6363636363636364

In [49]:
from sklearn.preprocessing import Binarizer

In [56]:
X_train.shape

(571, 3)

In [57]:
trf=ColumnTransformer([
    ('binarization',Binarizer(copy=False),['Family'])
],remainder='passthrough')

In [58]:
X_train_transformed=trf.fit_transform(X_train)
X_test_transformed=trf.transform(X_test)

In [59]:
X_test_transformed.shape

(143, 3)

In [64]:
pd.DataFrame(X_train_transformed,columns=['Family','Age','Fare'])

     Family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]

In [66]:
clf=DecisionTreeClassifier()
clf.fit(X_train_transformed,y_train)
y_pred=clf.predict(X_test_transformed)
accuracy_score(y_test,y_pred)

0.6153846153846154